### PR TITLE
Update for OpenBSD 7.2.

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Review by bradleysepos — APPROVED** [review]

**Comment by brad0** [comment]
Please commit. The release is now out.

**Comment by brad0** [comment]
BTW, how / when is handbrake.fr updated with the latest docs?

**Comment by bradleysepos** [comment]
> BTW, how / when is handbrake.fr updated with the latest docs?

I believe it's semi-automatic at the moment. I mostly amended your commit to ensure it had one of our verified GPG signatures attached. We used to rely on that to allow auto-building (perhaps still). @sr55 can clarify further but I believe someone has to push a big red button to deploy, for security reasons.

**Comment by brad0** [comment]
The reason I ask is it has been awhile since the initial OpenBSD bits were added but I don't see them up on the website.

**Comment by sr55** [comment]
Was this page ever added to the index menu?

I can see your changes are live but you get to them via the existing BSD page. 

image

**Comment by brad0** [comment]
Oh, maybe I missed something.

**Comment by sr55** [comment]
table-of-contents.markdown  has the menu structure

**Pull request merged**
