### PR TITLE
Update cli-options.markdown

### PR DESCRIPTION
**Pull request by ry8806**
some minor spelling mistakes

### CODE REVIEW

**Comment by sr55** [comment]
I'll give you an A for your master of irony, but your spelling is almost as bad as ours :)

**Comment by ry8806** [comment]
😂

Fat fingered that big-time!

**Comment by sr55** [comment]
Thanks!

**Comment by bradleysepos** [comment]
Thanks, will get this merged soon.

**Comment by bradleysepos** [comment]
Hah, GitHub hadn't refreshed the page data. Thanks all.

**Pull request merged**
