### PR TITLE
Add HDR10 and Universal Binary 2 for macOS

### PR DESCRIPTION
**Pull request by Nomis101**
I've tried to add a simple draft for HDR10 encoding. I used the video-bit-depth as a blueprint for that. And I've added information about the new UB2 for Mac. Hope thats fine.

### CODE REVIEW

**Comment by sr55** [comment]
Hey,

Do you have a GPG signing key?

**Comment by Nomis101** [comment]
> Hey,
> 
> Do you have a GPG signing key?

Now I have one.

**Comment by sr55** [comment]
Cool. Can you share your public key and if possible, re-commit this but signed.  I'll get you added to the safe list.

git config --global commit.gpgsign true
 git config user.signingkey  <your key>

You may or may not need to set 
git config --global gpg.program  <path-to-gpg>

too

**Comment by Nomis101** [comment]
OK, I've attached my public key and did all the "git config" commands. But I don't know how to resubmit all this signed.


[public.pgp.zip](https://github.com/HandBrake/HandBrake-docs/files/6633366/public.pgp.zip)

**Comment by sr55** [comment]
https://stackoverflow.com/questions/927358/how-do-i-undo-the-most-recent-local-commits-in-git  Looks like this will do it.

When you git commit again, it should automatically invoke gpg and request the password for the private key if you set one. Then the commit should be signed.

Force push and this PR should update. 


maybe keep a copy incase this goes side ways :)

**Pull request closed without merging**
