### PR TITLE
Add German Translation for the 1.1.0 HandBrake-docs

### PR DESCRIPTION
**Pull request by raderb**
Added German Translation for the 1.1.0 HandBrake-docs
Added first few linux pictures

### CODE REVIEW

**Comment by bradleysepos** [comment]
Wow, thank you very much. I will do a quick review, sign the commits, and get this merged.

In the near future we will likely be using Transifex/Crowdin to help manage translations. This will be an excellent basis for that. Thanks again and I hope you'll stick around to continue contributing. 😸

**Comment by raderb** [comment]
Glad to be able to help. I am most certainly going to stick around ;).

**Comment by bradleysepos** [comment]
One request, in the short term until we sort out the technical concerns and how we intend to manage translations, it's probably going to be easier to maintain English URLs. Any chance you have the time to make everything after de/ identical to the en/ version? `git mv ...` is your friend.

**Comment by bradleysepos** [comment]
Squashed and merged. Will go live the next time the docs build and publish. I can't say thank you enough!

**Pull request closed without merging**
