### PR TITLE
docs: Add OpenBSD initial documentation

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Comment by bradleysepos** [comment]
Looks like `automake-1.16.3` is the latest version available out of the box on OpenBSD 7.1.

**Comment by brad0** [comment]
> Looks like `automake-1.16.3` is the latest version available out of the box on OpenBSD 7.1.

Ah, yes. You're right. I was looking at the version with -current.

**Comment by brad0** [comment]
Updated. It is easy enough to bump back for 7.2.

**Comment by bradleysepos** [comment]
Ah, good to know. Is there really no good way to indicate to `pkg_add` to pick the latest in a release series, like `automake-1.16.x`? I suppose we could script trying to install `automake-1.16.99` through `automake-1.16.0`. Something like:

    for subver in $(seq 99 1); do sudo pkg_add "autoconf-2.$subver" && break; done
    for subver in $(seq 99 1); do sudo pkg_add "automake-1.16.$subver" && break; done

A bit ugly but perhaps better for longevity? I'm not sure whether there is anything we can easily do about `env AUTOCONF_VERSION=2.71`, though. Sigh.

**Comment by brad0** [comment]
> Ah, good to know. Is there really no good way to indicate to `pkg_add` to pick the latest in a release series, like `automake-1.16.x`? I suppose we could script trying to install `automake-1.16.99` through `automake-1.16.0`. Something like:
> 
> ```
> for subver in $(seq 99 1); do sudo pkg_add "autoconf-2.$subver" && break; done
> for subver in $(seq 99 1); do sudo pkg_add "automake-1.16.$subver" && break; done
> ```
> 
> A bit ugly but perhaps better for longevity? I'm not sure whether there is anything we can easily do about `env AUTOCONF_VERSION=2.71`, though. Sigh.

I have never seen anything like that before. You can have whatever installed. It's just what is installed / used needs to be also what the value of AUTOCONF_VERSION is.

**Comment by bradleysepos** [comment]
All right, I'll avoid complicating matters with scripting. We will just need to ensure that the dependency versions match the listed OpenBSD version, so the article remains self-contained and the instructions reproducible. I will also assume OpenBSD users will generally be knowledgeable enough to make package decisions in the event the article is not updated in perfect timing with each -current release.

**Comment by brad0** [comment]
> All right, I'll avoid complicating matters with scripting. We will just need to ensure that the dependency versions match the listed OpenBSD version, so the article remains self-contained and the instructions reproducible. I will also assume OpenBSD users will generally be knowledgeable enough to make package decisions in the event the article is not updated in perfect timing with each -current release.

Yes, I would think so. Versions for things like this don't tend to change much in autotools land. and a version like automake going +1 for the minor typically is no big deal.

**Comment by bradleysepos** [comment]
Noticed one minor issue, it seems `libvpx` is located under graphical interface dependencies?

**Comment by brad0** [comment]
> Noticed one minor issue, it seems `libvpx` is (also) located under graphical interface dependencies?

Ah. That is also the case for the FreeBSD and NetBSD pages. But yes, it shouldn't be specific to the GUI part.

**Comment by bradleysepos** [comment]
> > Noticed one minor issue, it seems `libvpx` is (also) located under graphical interface dependencies?
> 
> Ah. That is also the case for the FreeBSD and NetBSD pages. But yes, it shouldn't be specific to the GUI part.

Definitely my typo then. Will fix in post.

**Comment by bradleysepos** [comment]
Rebased and merged, thanks!

**Pull request merged**
