### PR TITLE
Translate updated Dependencies Installation Instructions for CentOS (German)

### PR DESCRIPTION
**Pull request by raderb**
Updated the German Translation for the CentOS Dependencies Installation article.

### CODE REVIEW

**Comment by bradleysepos** [comment]
Hi @raderb, try this (replace upstream and origin with your HandBrake and personal repo remotes):

```
git checkout master
git pull --ff-only upstream master
git checkout centosgtk
git rebase master
git push --force centosgtk
```

If everything goes well, you should see the commit(s) on this feature branch with updated hashes, and they should now be signed. A Verified badge will display on each signed commit on the GitHub website.

image

**Comment by bradleysepos** [comment]
Oops, I almost forgot. You will also need to go to GitHub Settings > SSH and GPG keys and add your GPG public key for the Verified badge to work.

**Comment by bradleysepos** [comment]
That worked. 😸 Merged. Note also that I revised the CentOS instructions slightly in https://github.com/HandBrake/HandBrake-docs/commit/7944285e77852a9de18145b9392a47e8a03723a1.

You can now push your work directly to the upstream master branch. Prefix your commit messages with "docs: de:" if you can, no worries if you forget. You can still open pull requests for anything you would like feedback on.

Hopefully having commit access makes things easier for you. Thanks again for all your help! Glad to have you on the team! 🎉 🎈

**Comment by raderb** [comment]
Glad to be able to help ;)

**Pull request closed without merging**
